name: Larastan (PHPStan)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  larastan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up PHP
        uses: ./.github/actions/setup
        with:
          php-version: '8.3'
          php-extensions: 'mbstring, xml, tokenizer, curl, json'

      - name: Install Composer Dependencies
        run: composer install --no-progress --prefer-dist

      - name: Run Larastan
        run: |
          vendor/bin/phpstan analyse --no-progress --configuration=phpstan.neon --memory-limit=2G
