name: Rector (Instant Upgrades and Automated Refactoring)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  rector:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ["8.2", "8.3"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          php-version: ${{ matrix.php }}
          php-extensions: "mbstring, xml, tokenizer, curl, json"

      - name: Install PHP dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --no-interaction

      - name: Cache Rector cache
        uses: actions/cache@v4
        with:
          path: storage/rector
          key: ${{ runner.os }}-rector-${{ hashFiles('**/rector.php') }}
          restore-keys: ${{ runner.os }}-rector-

      - name: Run Rector
        run: vendor/bin/rector process --ansi --dry-run --no-diffs
        # continue-on-error: true # Allow it to continue for reporting

      - name: Auto-fix Rector Changes (Optional)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          vendor/bin/rector process --ansi
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "chore: apply Rector fixes" || echo "No changes to commit"
          git push origin main || echo "No changes to push"

      - name: Validate Rector changes
        run: git diff --exit-code
